### ISSUE TITLE
Automatic reference downloader doesnt kick in

### ISSUE THREAD

**Issue by sylvinite** [Clinical-Genomics/microSALT#122]
**Describe the bug**
Automatic reference downloader doesnt kick in.

**To Reproduce**
Remove an existing reference or add a new one. It wont be downloaded by microSALT.

**Expected behavior**
Its expected to be downloaded.

**Additional context**
It could possibly be due to changes in NCBIs API. Or a timeout issue. Or the reference name is parsed incorrectly
Identified through sample ACC7248A23

**Comment by talnor** [comment]
This is fixed as of #123.
