### ISSUE TITLE
Emails with reports from slurm not received

### ISSUE THREAD

**Issue by talnor** [Clinical-Genomics/microSALT#124]
**Describe the bug**
It seems like emails that are sent from slurm are not recieved. I.e. no emails are sent when an analysis run finishes. Reports are however sent when running microsalt utils report manually. Makes it difficult to keep track of when microbial analyses are done.

**To Reproduce**
Run the following as bash and sbatch:
- source activate P_microSALT
- microSALT utils report /home/proj/production/microbial/queries/934197.json --email <>@scilifelab.se

**Comment by sylvinite** [comment]
One possibility is that the HPC is so full that it can't generate the e-mails.
Another one is that Google filters them as spam.

**Comment by talnor** [comment]
With "anyone on the web can post" emails are received. The sender email address is not listed as a member in the group. I am not able to currently add it, but maybe owner Isak can attempt it.

**Comment by vwirta** [comment]
which e-mail group are the emails sent to?

**Comment by sylvinite** [comment]
The mails are sent through ClinicalDelivery. Temporarily elevated @talnor to owner level.
With great power, etc etc.

**Comment by vwirta** [comment]
@talnor when I check the group settings, it says that 'Entire organisation' can post. 
'Anyone on the web' cannot post. 
Microsalt and root are considered external.

**Comment by talnor** [comment]
I agree. I temporarily set it to "anyone on the web" for debugging. Still can't add the external members properly. Might be due to scilifelab settings for our google groups (https://support.google.com/a/answer/167097).

**Comment by sylvinite** [comment]
Now it's working again.
