### ISSUE TITLE
Add catch for samples mixed with same species

### ISSUE THREAD

**Issue by talnor** [Clinical-Genomics/microSALT#128]
**Is your feature request related to a problem? Please describe.**
We can expect samples to be contaminated on rare occasions. If a sample should be contaminated by a another sample of the same species, the typing results might be affected. It would be good to have a way of catching these cases and ensure they are not marked as passed.

There are two possible outcomes affecting the typing of such a sample:
1. One or more loci lack a contig that completely covers the region (currently marked as failed)
2. One or more loci have several contigs that completely covers the region

**Describe the solution you'd like**
Implement a check for outcome 2 and mark such samples in the typing report.

**Comment by pbiology** [comment]
Issue considered in JASEN
