### ISSUE TITLE
Add fields in the report for important resistances

### ISSUE THREAD

**Issue by talnor** [Clinical-Genomics/microSALT#141]
**Is your feature request related to a problem? Please describe.**

Additional fields for resistances are requested by KS. 
- New columns in the summary of the typing report: ”Anmälningspliktig resistens”, ”Genkategori”
- New column in the sample-level resistance table: ”Kategori”

The fields should more clearly mark out samples with resistances of high concern. 

**Describe the solution you'd like**
-

**Describe alternatives you've considered**
-

**Additional context**

> Vi har arbetat med ett projekt med syfte att förenkla tolkningen av resistensgenerna i MikroSALT rapporten för personalen som svarar ut, vilket vi har diskuterat på flera epitypningsmöten under våren.
> Syftet är att man redan i översikten i rapporten ska kunna se om isolatet är ESBL-CARBA, ESBL, MRSA eller VRE. Detta för att kunna reagera och utföra felsökning om man har typat ett isolat som man tror bär en anmälningspliktig resistens, men det visar sig att det inte har det. 
>  
> Vi har kodat resistensgenerna i resfinder i bifogad och vill att denna info ska visas både i översikten och i detaljinfon för varje gen (kategorierna som anges skiljer sig lite grann mellan de två delarna).
> Vi har försökt förtydliga hur vi tänker oss att kategorierna ska visas i bifogad ppt.
>  
> Det är tre olika kolumner vi önskar (Förslag på rubriker – men kommer ni på bättre och kortare rubriker, föreslå gärna det):
> Översiktsvyn – ”Anmälningspliktig resistens” och ”Genkategori”
> Detaljinfo för varje isolat -  ”Kategori”
>  
> Tror ni att något i denna stil är möjligt att skapa?
> Återkom gärna med frågor och förslag!
>  
> Mvh
> Inga

**Comment by pbiology** [comment]
Moved to Clinical-Genomics/CG-JASEN#2
