### ISSUE TITLE
Make validation samples available

### ISSUE THREAD

**Issue by talnor** [Clinical-Genomics/microSALT#144]
**Describe the bug**
The following projects are used to validate microSALT: MIC3109, MIC4107, MIC4109 & ACC5551.

* Only ACC5551 can be found in statusDB/housekeeper.
* ACC5551 has spring-compressed samples that cannot be decompressed with `cg decompress`. On closer inspection, the case is a mix of validation and routine samples. May be a good idea to have a separate case for the validation samples only. 

**Expected behavior**
All cases and samples should be available for validations in cg.

**Additional context**

> Updating compress api
> Set dry run to False
> Fetch latest version from bundle ACC5551A31
> Found file /home/proj/production/demultiplexed-runs/190417_A00621_0064_AHJM7JDSXX/Unaligned-Y151I10I10Y151/Project_609108/Sample_ACC5551A31/HJM7JDSXX_609108_S313_L004.spring
> Found file /home/proj/production/demultiplexed-runs/190417_A00621_0064_AHJM7JDSXX/Unaligned-Y151I10I10Y151/Project_609108/Sample_ACC5551A31/HJM7JDSXX_609108_S313_L002.spring
> Found file /home/proj/production/demultiplexed-runs/190417_A00621_0064_AHJM7JDSXX/Unaligned-Y151I10I10Y151/Project_609108/Sample_ACC5551A31/HJM7JDSXX_609108_S313_L001.spring
> Found file /home/proj/production/demultiplexed-runs/190417_A00621_0064_AHJM7JDSXX/Unaligned-Y151I10I10Y151/Project_609108/Sample_ACC5551A31/HJM7JDSXX_609108_S313_L003.spring
> Check if pending compression file exists
> /home/proj/production/demultiplexed-runs/190417_A00621_0064_AHJM7JDSXX/Unaligned-Y151I10I10Y151/Project_609108/Sample_ACC5551A31/HJM7JDSXX_609108_S313_L004.crunchy.pending.txt does not exist
> Check if SPRING archive file exists
> Check if FASTQ pair exists
> FASTQ files already exists
> SPRING to FASTQ decompression not possible for ACC5551A31
> Skipping sample ACC5551A31

**Comment by pbiology** [comment]
Will be part of validation strategy in JASEN.
Clinical-Genomics/CG-JASEN#3
