### ISSUE TITLE
Changing Allel information in typing report for Novel allels

### ISSUE THREAD

**Issue by Vince-janv** [Clinical-Genomics/microSALT#146]
This request was made by cust056 in ticket [533193](https://clinical-scilifelab.supportsystem.com/scp/tickets.php?id=43439).

**Is your feature request related to a problem? Please describe.**
Customer thinks assigning the closest allel to a Loci if the identity is not 100%, is misleading. 

**Describe the solution you'd like**
Customer suggests any of the following information in the field instead:
- Novel 
- Novel (allelnummer som liknar mest), t ex Novel (3)
- (allelenummer som liknar mest), t ex (3) eller 3*

**Update 2022-01-19:**
cust056 has also requested to have the `sekvenstyp` in the summary table set to  `okänd` for the samples that fail the thresholds. 

**Additional context**
Screenshot of the field in question is shown below:
![Screenshot 2021-09-20 at 13 11 26 (1)](https://user-images.githubusercontent.com/69356202/134139317-48f24083-172b-44b9-8edf-965036ed3994.png)

Screenshot of the field in the summary table:
![resultatsammanstallning_ex](https://user-images.githubusercontent.com/35598351/150153526-9b765a27-2b22-410c-8e75-e3f4a375db29.png)

**Comment by pbiology** [comment]
Will be continued in JASEN
Clinical-Genomics/CG-JASEN#4
