### ISSUE TITLE
Add automatic blacking

### ISSUE THREAD

**Issue by talnor** [Clinical-Genomics/microSALT#148]
**Is your feature request related to a problem? Please describe.**
Automatically run black to reformat the structure of the code in new PRs. 

**Describe the solution you'd like**
* Figure out how automatic blacking works
* Implement this in microSALT

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by talnor** [comment]
Also see similar issue in mutant: https://github.com/Clinical-Genomics/MUTANT/issues/105

**Comment by henrikstranneheim** [comment]
You can add it to a github workflow - like this: https://github.com/Clinical-Genomics/atlas/blob/master/.github/workflows/black.yml

or install it in your editor: https://black.readthedocs.io/en/stable/integrations/editors.html

or install it via pre-commit: https://pre-commit.com/, see for instance: https://github.com/Clinical-Genomics/atlas/blob/master/.pre-commit-config.yaml

**Comment by pbiology** [comment]
Not for microSALT
