### ISSUE TITLE
What should we trend in vogue for microsalt?

### ISSUE THREAD

**Issue by henningonsbring** [Clinical-Genomics/microSALT#156]
Trending statistics from microsalt analyses in vogue can give an insight into the quality of the lab work performed by Clinical genomics. We need to decide which metrics to monitor.

The metrics that matters when we deliver data to the customers:
- Number of reads
- 10x coverage
- If typing was successful

What I suggest we trend:
- Fraction of samples that get the ordered number of reads
- 10x coverage for MWR app tags
- If typing was successful for MWR app tags

Data shown by vogue won't say much about the quality of our work at Clinical genomics, basically all metrics are affected by what the customer write when they make the order. If a customer write wrong species, or submit a contaminated sample, then coverage will be low and the typing will fail.

The only important metric I can think off that we fully control if we reach the ordered number of reads or not for the samples. The customers that order MWR usually order well known patogens with support for typing by the pubMLST database, that also will be easy to type with MALDI-TOF. Therefore, the reference from start tend to be correct and vary less for the MWR-orders. For the research app tags the effort is very low when it comes to guess what species that is submitted. Because of this I suggest 10x coverage and successful typing is only tracked for MWR app tags.

Is it possible to only track metrics for a certain app tag? What do you think about my suggestion regarding metrics to pay attention to? @moahaegglund @talnor @karlnyr @Vince-janv @Karl-Svard @keyvanelhami 

This issue can be closed when we have agreed on what metrics we should pay extra attention for monitoring the quality of microsalt orders over time.

**Comment by karlnyr** [comment]
I agree with these metrics! If we are including success rate if typing we may also include frequency of novel/unknown allele types per sample? Else, are you only going to look for the "Godkänd" criterium?

**Comment by henningonsbring** [comment]
> I agree with these metrics! If we are including success rate if typing we may also include frequency of novel/unknown allele types per sample? Else, are you only going to look for the "Godkänd" criterium?

I agree, if we can extract information regarding how many novel alleles we find over time that would be highly relevant as a complement to the success rate for typing.

**Comment by henningonsbring** [comment]
<img width="835" alt="Screenshot 2022-03-01 at 10 35 17" src="https://user-images.githubusercontent.com/66672810/156143453-4f07cdbc-6dba-4913-bc3a-c434bf3e40e5.png">

"If typing was successful for MWR app tags" can be more clearly defined by "Was the 'tröskelvärden' = 'Godkända'"

**Comment by talnor** [comment]
Sounds great! It sounds like a good idea to have the option of splitting the data by apptag as you suggest.

Regarding the metrics some of them are present in vouge already. Number of reads i don't think is added by microSALT at least. Would be good to have a look at what we have now and define what we think is missing.

**Comment by talnor** [comment]
Perfect! I think we can make an issue for the suggested improvements. Then it can be picked up when we have more developers working on Vogue.

**Comment by pbiology** [comment]
Continued in Clinical-Genomics/CG-JASEN#6
