### ISSUE TITLE
Replace travis with github actions

### ISSUE THREAD

**Issue by talnor** [Clinical-Genomics/microSALT#157]
**Is your feature request related to a problem? Please describe.**
Reported security issues with Travis as described here: https://github.com/Clinical-Genomics/IT-issues/issues/531#issuecomment-1114796350

**Describe the solution you'd like**
Replace Travis-CI with github actions.

**Describe alternatives you've considered**

**Additional context**

**Comment by pbiology** [comment]
Not priority for microSALT
