### ISSUE TITLE
Change report to follow accreditation guidelines

### ISSUE THREAD

**Issue by emmser** [Clinical-Genomics/microSALT#44]
Add things to report that is required by accreditation
7.8.2.1
 - [x] Titel
 - [x] Laboratory name and adress (Clinical genomics)
 - [x] End of report
 (- [ ] Page numbers - skipping that for now)
 - [x] Customer name and contact information - INSTEAD use CustID (statusDB)
 - [x] Application tag  (LIMS)
 - [x] cust-id (LIMS) (to be able to show customer information in AM/statusDB)
 - [x] Version of uSALT (from where?)
 - [x] Description of the sample-object, = sampleID
 - [x] Dates for reception, library prep, sequencing and analysis (LIMS)
 - [x] Method document and version (Sequencing and Library prep)
 - [x] Date for printing of report
 - [x] The result
 - [x] Deviations from the method 
 - [x] Identification of the person(s) approving the report
 - [x] Teknisk beskrivning av analysen (nu hårdkodad text - i framtid från statusDB)
 - [x] Begränsningar av analysen (nu hårdkodad text - i framtid från statusDB)
 - [x] Översätt till svenska - åäö problem

 7.8.2.2
 - [x] Separate table holding information from customer/star for customer information
 - [x] Friskrivningsklausul "The results apply to the sample that has been provided customer"

**Comment by sylvinite** [comment]
Other aspects to consider:
Display of which microSALT version used (and in turn version of individual software)
SWEDAC logo
Declaration of samples excluded from accreditation
Information as to what exactly the accreditation entails
Clarification of key variables, e.g. 'span'?

**Comment by emmser** [comment]
Updating to master:

- [ ] Update version
- [ ] Update path to Swedac-logo

**Comment by sylvinite** [comment]
Resolved in #64
