### ISSUE TITLE
Improve code coverage to 85%

### ISSUE THREAD

**Issue by sylvinite** [Clinical-Genomics/microSALT#94]
Improve the reported coveralls coverage ( https://coveralls.io/github/Clinical-Genomics/microSALT?branch=master ) by further improving the tests provided in https://github.com/Clinical-Genomics/microSALT/tree/master/tests until a **85%** coverage is reached.

- [x] 50%
- [x] 55%
- [x] 60%
- [x] 65%
- [x] 70%
- [x] 75%
- [x] 80%
- [ ] 85%
- [ ] 90%
- [ ] 95%

**Comment by pbiology** [comment]
Skipped due to working on JASE instead
